Train:
  batch_size: 32
  learning_rate: 0.001
  reg: 0.0001
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1.0

network:
  model: MyModel # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: regular # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal
